version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql_tfg
    restart: always
    environment:
      MYSQL_DATABASE: tfg_db_prod
      MYSQL_USER: tfg_user
      MYSQL_PASSWORD: tfg_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: springboot_tfg
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend/aitstore-frontend
    container_name: angular_tfg
    restart: always
    ports:
      - "4200:80"

volumes:
  db_data:
